site_name: USC CTIN583 Game Development (Fall 2023)
site_url: https://usc-ctin583.github.io/

  
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: purple
      accent: purple
  extra_css: 
    - stylesheets/extra.css


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/USCCinema
    - icon: fontawesome/brands/discord
      link: https://discord.com/channels/343612930056781825/687390873197084672


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 

copyright: |
  &copy; 2023 <a href="https://github.com/debbieyuen"  target="_blank" rel="noopener">Debbie Yuen</a>

